export interface ReducedModeConfig {
  MAX_UNIQUE_TOKENS: number;
  MIN_UNIQUE_TOKENS: number;
  TRENDING_RATIO_TARGET: number;
  VOLUME_RATIO_TARGET: number;
  DISCREPANCY_THRESHOLD: number;
  MIN_DATA_COMPLETENESS: number;
  DEXSCREENER_FETCH_TARGET: number;
  DEXPAPRIKA_FETCH_TARGET: number;
  CANDIDATE_POOL_TARGET_PRE_DEDUPE: number;
  PAGINATION_MIN_USABLE: number;
  MAX_RECOVERY_ATTEMPTS: number;
  BACKOFF_BASE_MS: number;
  BACKOFF_FACTOR: number;
  BACKOFF_JITTER_PERCENT: number;
  enableSocial: boolean;
  enableMoralis: boolean;
  enableRpcVerify: boolean;
  CACHE_DEX_STALENESS_MS: number;
  CACHE_SOCIAL_STALENESS_MS: number;
}

export const DEFAULT_REDUCEDMODE_CONFIG: ReducedModeConfig = {
  MAX_UNIQUE_TOKENS: 30,
  MIN_UNIQUE_TOKENS: 20,
  TRENDING_RATIO_TARGET: 0.5,
  VOLUME_RATIO_TARGET: 0.5,
  DISCREPANCY_THRESHOLD: 0.20,
  MIN_DATA_COMPLETENESS: 70,
  DEXSCREENER_FETCH_TARGET: 25,
  DEXPAPRIKA_FETCH_TARGET: 25,
  CANDIDATE_POOL_TARGET_PRE_DEDUPE: 60,
  PAGINATION_MIN_USABLE: 20,
  MAX_RECOVERY_ATTEMPTS: 3,
  BACKOFF_BASE_MS: 500,
  BACKOFF_FACTOR: 2.0,
  BACKOFF_JITTER_PERCENT: 20,
  enableSocial: false,
  enableMoralis: false,
  enableRpcVerify: false,
  CACHE_DEX_STALENESS_MS: 15 * 60 * 1000,
  CACHE_SOCIAL_STALENESS_MS: 45 * 60 * 1000,
};
